site_name: NERDA
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
  - mknotebooks:
      execute: True

nav:
    - Home: index.md
    - Workflow Examples: tester.ipynb
    - Code Reference:
        - NERDA Models: nerda_models.md
        - Precooked NERDA Models: precooked_models.md
        - Datasets: datasets.md

