site_name: NERDA
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
       python:
          setup_commands:
            - import sys
            - sys.path.append("src")

nav:
    - Home: index.md
    - Code Reference:
        - Datasets: datasets.md
