#---------------------------------------------------------------------
# GitHub Actions Workflow to Test, Build and Publish Package
#
#---------------------------------------------------------------------
name: build
    
on: [push]

jobs:

  Pipeline:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Cache Python packages
      uses: actions/cache@v2
      with: 
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install pip
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
    
    - name: Run tests
      run: |
        python setup.py test

    - name: Build and publish
      if: github.ref == 'refs/heads/main'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install -r dev-requirements.txt
        python setup.py sdist bdist_wheel
        twine upload upload dist/*
    