#---------------------------------------------------------------------
# GitHub Actions Workflow to Test, Build and Publish Package
#
#---------------------------------------------------------------------
name: build
    
on: [push]

jobs:

  Pipeline:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region           : ${{ env.AWS_REGION_NAME }}
    
    - name: Cache Python modules
      uses: actions/cache@v2
      with: |
        path: ~/.cache/pip
      key: ${{runner.os}}-python

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install setuptools twine wheel
    
    - name: Run tests
      run: |
        python setup.py test

    - name: Build and publish
      if: github.ref == 'refs/heads/main'
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository codeartifact dist/*
    