#---------------------------------------------------------------------
# GitHub Actions Workflow to build and publish Documentation.
#
#---------------------------------------------------------------------
name: docs
    
on: [push]
  branches: main


jobs:

  Documentation:
    needs: Build

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Cache Python packages
      uses: actions/cache@v2
      with: 
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install pip and dev requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt

    - name: Deploy docs
      run: |
        pip install .
        mkdocs gh-deploy --force